### ISSUE TITLE
[Feature Request] Allow customisation of "share with" links

### ISSUE THREAD

**Issue by deosrc** [wayjam/hugo-theme-fluidity#2]
I think there are 3 levels to the customisation which could be added here:

1. Disable share with: Currently it seems it can only be disabled by section.
2. Allow items to be removed (list in site params)
3. Allow additional items to be added (via additional layout files and adding to site params list)

![Image](https://github.com/user-attachments/assets/c534245f-0431-436f-a9d4-b0bc605233bc)

Theme is looking really nice!

**Comment by wayjam** [comment]
@deosrc What do you think of this implementation? https://github.com/wayjam/hugo-theme-fluidity/pull/8

```yaml
  social:
    twitter: 'Your Twitter username'
    github: 'Your GitHub username'
    linkedin: 'Your LinkedIn username'

    share:
      disabled: false
      disableByType: # content type
        - not-exist
      platforms: # available inherit platform: [redidit, x, facebook, google, telegram]
        - name: reddit # inherit platform just need the name
        - name: x
        - name: facebook
        - name: google
        # - name: telegram # disable the inherit platform
        - name: Linkedin # this is a custom platform
          url: "https://www.linkedin.com/shareArticle?url=%s&title=%s" # args(Permalink, Title)
        - name: WhatsApp
          url: "https://wa.me/?text=%s %s"
    connect:
      platforms: # available inherit platform: [github, x, linkedin]
        - github
        - x
        - linkedin
```
